/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelompokproject;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;



/**
 *
 * @author Tinkpad
 */
public class Kegiatan extends javax.swing.JFrame {
    private int idUser;
    
    public Kegiatan(int idUser, String namaUser, String umurUser) {
        this.idUser = idUser;
        initComponents();
        nama.setText(namaUser);
        umur.setText(umurUser);
        Total_Kalori.setEditable(false);
        tampil_aktivitas.setEditable(false);
    }

    /**
     * Creates new form Kegiatan
     */
    public Kegiatan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        larijarakmenengah = new javax.swing.JCheckBox();
        yoga = new javax.swing.JCheckBox();
        Senam = new javax.swing.JCheckBox();
        latihankardio = new javax.swing.JCheckBox();
        jalancepat = new javax.swing.JCheckBox();
        jalansantai = new javax.swing.JCheckBox();
        pushup = new javax.swing.JCheckBox();
        bersepeda = new javax.swing.JCheckBox();
        renang = new javax.swing.JCheckBox();
        simpan = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampil_aktivitas = new javax.swing.JTextArea();
        Total_Kalori = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(91, 196, 108));

        jLabel1.setText("Nama");

        jLabel2.setText("Umur");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        larijarakmenengah.setText("Lari Jarak Menengah");
        larijarakmenengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larijarakmenengahActionPerformed(evt);
            }
        });

        yoga.setText("Yoga");
        yoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yogaActionPerformed(evt);
            }
        });

        Senam.setText("Senam");

        latihankardio.setText("Latihan Kardio");
        latihankardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latihankardioActionPerformed(evt);
            }
        });

        jalancepat.setText("Jalan Cepat");

        jalansantai.setText("Jalan Santai");

        pushup.setText("Push Up");

        bersepeda.setText("Bersepeda");
        bersepeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersepedaActionPerformed(evt);
            }
        });

        renang.setText("Renang");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel5.setText("Total Kalori");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tampil_aktivitas.setColumns(20);
        tampil_aktivitas.setRows(5);
        jScrollPane1.setViewportView(tampil_aktivitas);

        Total_Kalori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_KaloriActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 89));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Aktivitas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel6)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTextField1.setBackground(new java.awt.Color(255, 255, 89));
        jTextField1.setText("Aktivitas selama 30 menit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(larijarakmenengah)
                                    .addComponent(latihankardio)
                                    .addComponent(jalancepat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bersepeda)
                                    .addComponent(pushup)
                                    .addComponent(Senam))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yoga)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpan)
                                .addGap(49, 49, 49)
                                .addComponent(reset)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(renang)
                                    .addComponent(jalansantai)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Total_Kalori, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(larijarakmenengah)
                            .addComponent(pushup))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bersepeda)
                            .addComponent(yoga)
                            .addComponent(latihankardio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Senam)
                            .addComponent(jalansantai)
                            .addComponent(jalancepat)))
                    .addComponent(renang))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(reset)
                    .addComponent(simpan))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total_Kalori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String aktivitas;
        aktivitas ="";
        int totalkalori = 0;
        
        if(larijarakmenengah.isSelected()){
            aktivitas += larijarakmenengah.getText()+ ", ";
            totalkalori += 295;
        }
        if(yoga.isSelected()){
            aktivitas += yoga.getText()+ ", ";
            totalkalori += 140;
        }
        if(Senam.isSelected()){
            aktivitas += Senam.getText()+ ", ";
            totalkalori += 175;
        }
        if(latihankardio.isSelected()){
            aktivitas += latihankardio.getText()+ ", ";
            totalkalori += 250;
        }
        if(jalancepat.isSelected()){
            aktivitas += jalancepat.getText()+ ", ";
            totalkalori += 175;
        }
        if(jalansantai.isSelected()){
            aktivitas += jalansantai.getText()+ ", ";
            totalkalori += 140;
        }
        if(pushup.isSelected()){
            aktivitas += pushup.getText()+ ", ";
            totalkalori += 250;
        }
        if(bersepeda.isSelected()){
            aktivitas += bersepeda.getText()+ ", ";
            totalkalori += 245;
        }
        if(renang.isSelected()){
            aktivitas += renang.getText() + ", ";
            totalkalori += 220;
}

if (!aktivitas.isEmpty()) {
    aktivitas = aktivitas.substring(0, aktivitas.length() - 2); // hapus koma terakhir
    tampil_aktivitas.setText(aktivitas);
    Total_Kalori.setText(totalkalori + " Kkal");
    
    try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/profilbaru", "root", "");
    String query = "INSERT INTO kegiatan (id_user, nama, umur, aktivitas, total_kalori) VALUES (?, ?, ?, ?, ?)";
    PreparedStatement pst = conn.prepareStatement(query);
    
    pst.setInt(1, idUser);
    pst.setString(2, nama.getText());         
    pst.setString(3, umur.getText());        
    pst.setString(4, aktivitas);             
    pst.setInt(5, totalkalori); 
    
    pst.executeUpdate();
    System.out.println("ID User: " + idUser);
    JOptionPane.showMessageDialog(null, "Aktivitas berhasil disimpan!");
    
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Gagal simpan aktivitas: " + ex.getMessage());
}
    }//GEN-LAST:event_simpanActionPerformed
    }
    private void bersepedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersepedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bersepedaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
    larijarakmenengah.setSelected(false);
    yoga.setSelected(false);
    Senam.setSelected(false);
    latihankardio.setSelected(false);
    jalancepat.setSelected(false);
    jalansantai.setSelected(false);
    pushup.setSelected(false);
    bersepeda.setSelected(false);
    renang.setSelected(false);
    tampil_aktivitas.setText("");
    larijarakmenengah.requestFocus();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        home homeframe = new home ();
        homeframe.setVisible(true);
        homeframe.pack ();
        homeframe.setLocationRelativeTo(null);
    this.dispose ();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void larijarakmenengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larijarakmenengahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_larijarakmenengahActionPerformed

    private void latihankardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latihankardioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latihankardioActionPerformed

    private void Total_KaloriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_KaloriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_KaloriActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void yogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yogaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kegiatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Senam;
    private javax.swing.JTextField Total_Kalori;
    private javax.swing.JCheckBox bersepeda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox jalancepat;
    private javax.swing.JCheckBox jalansantai;
    private javax.swing.JCheckBox larijarakmenengah;
    private javax.swing.JCheckBox latihankardio;
    private javax.swing.JTextField nama;
    private javax.swing.JCheckBox pushup;
    private javax.swing.JCheckBox renang;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTextArea tampil_aktivitas;
    private javax.swing.JTextField umur;
    private javax.swing.JCheckBox yoga;
    // End of variables declaration//GEN-END:variables
}
